### ISSUE TITLE
Create the basic layout and structure of the website.

### ISSUE THREAD

**Issue by RiveraSonoely-FS** [RiveraSonoely-FS/YYMM-WDV349-RiveraSonoely#3]
**Install Dependencies**
-Install react-router-dom

**Organize the project into logical folders**

**Create Basic Components**
-Header: Contains the website title and navigation links (Home, About, Projects).
-Footer: Contact info, GitHub link, and social media links.
-Home Page: A short introduction with a brief summary of who I am.
-About Page: A more detailed description of my skills, experience, and projects.
-Projects Page: A portfolio of my past work with links to GitHub repositories.

**Comment by Nandini1071** [comment]
Hi @RiveraSonoely-FS Is this issue still open , if yes would like to contribute on this, please let me know.

**Comment by RiveraSonoely-FS** [comment]
Basic structure has been complete.
